spring.application.name=weather

owm.api-key=${OWM_API_KEY}
owm.base-url=https://api.openweathermap.org/data/3.0/onecall

ipapi.base-url=http://ip-api.com/json/

cors.allowed-origins=https://yousefelghoul.gitlab.io,http://localhost